### ISSUE TITLE
Focus to last tab when closing tab

### ISSUE THREAD

**Issue by timscott** [oggy/tab-switcher#11]
This package fixes the horrible default tab switching behavior in Atom. Except when I close a tab, it still focusses the tab to the left of the closed tab instead of last tab. It would be awesome if this package could add that. Thanks!

**Comment by oggy** [comment]
I agree with the idea, but I believe I'll need [some help](https://github.com/atom/atom/pull/7395) from Atom core.

Thanks for the suggestion!

**Comment by guillaume86** [comment]
@oggy nice extension, you can probably achieve the same feature with a little workaround, I managed to do it in my (now deprecated) extension: 

https://github.com/guillaume86/tab-history/commit/929c93319c56524ac58a7a58239ba1c7b4b1589f

Side note: thanks for the work, using this one to replace mine now. You should add "MRU tab switching" somewhere in your extension description because it's a commonly used term to define that behavior.

**Comment by oggy** [comment]
Thanks @guillaume86! Neat trick -- I'll resort to something like that if that PR doesn't get merged into Atom soon.

Good call on the description. I called it "least recently used" tab switching, but I agree that's the opposite of what it is.
