### ISSUE TITLE
tab switcher popup close

### ISSUE THREAD

**Issue by nisalavira** [oggy/tab-switcher#16]
tab switcher popup closing if i take my finder from the alt key it is annoying. But while it open if i check on other window and come back to atom it is in there. can you fix this and give a tab search in that popup  as sublime text does?

**Comment by oggy** [comment]
Thanks for the feedback. Just pushed a fix for hiding the tab list if the window loses focus. Will publish shortly.

The tab list disappearing when you release the modifier key is by design. If you want a list that you can arrow through and hit enter, perhaps the built-in `fuzzy-finder:toggle-buffer-finder` does what you want. Otherwise I'm not quite sure what you're after. That built-in buffer finder also lets you filter the list by typing.
